"""empty message

Revision ID: 12a6601db941
Revises: 399e730a73b7
Create Date: 2014-04-24 20:23:09.298190

"""

# revision identifiers, used by Alembic.
revision = '12a6601db941'
down_revision = '399e730a73b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('category', sa.Unicode(length=64), nullable=True))
    op.add_column('music', sa.Column('tag', sa.Unicode(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music', 'tag')
    op.drop_column('music', 'category')
    ### end Alembic commands ###
