"""empty message

Revision ID: 12e23721e75f
Revises: 195a7d647fc5
Create Date: 2014-03-31 15:18:16.495043

"""

# revision identifiers, used by Alembic.
revision = '12e23721e75f'
down_revision = '195a7d647fc5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
