"""empty message

Revision ID: 195a7d647fc5
Revises: 222f2955787e
Create Date: 2014-03-31 12:30:12.899153

"""

# revision identifiers, used by Alembic.
revision = '195a7d647fc5'
down_revision = '222f2955787e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=128), nullable=True),
    sa.Column('url', sa.Unicode(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'users', 'confirmed_at')
    op.create_index('ix_users_google_user_id', 'users', ['google_user_id'], unique=True)
    op.drop_index('ix_users_email', 'users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_index('ix_users_google_user_id', 'users')
    op.add_column(u'users', sa.Column('confirmed_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_table('music')
    ### end Alembic commands ###
