"""empty message

Revision ID: 222f2955787e
Revises: 493eb79079a1
Create Date: 2014-02-05 15:08:27.698585

"""

# revision identifiers, used by Alembic.
revision = '222f2955787e'
down_revision = '493eb79079a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token')
    ### end Alembic commands ###
