"""empty message

Revision ID: 329ffae13ec0
Revises: 12e6133f3f62
Create Date: 2014-02-02 19:51:38.181009

"""

# revision identifiers, used by Alembic.
revision = '329ffae13ec0'
down_revision = '12e6133f3f62'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection', 'secret')
    op.drop_column('connection', 'display_name')
    op.drop_column('connection', 'rank')
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', 'user')
    op.add_column('connection', sa.Column('rank', sa.INTEGER(), nullable=True))
    op.add_column('connection', sa.Column('display_name', sa.VARCHAR(length=255), nullable=True))
    op.add_column('connection', sa.Column('secret', sa.VARCHAR(length=255), nullable=True))
    ### end Alembic commands ###
