"""empty message

Revision ID: 377217156942
Revises: 2ea2c6319994
Create Date: 2014-04-03 21:38:59.100213

"""

# revision identifiers, used by Alembic.
revision = '377217156942'
down_revision = '2ea2c6319994'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.Unicode(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    ### end Alembic commands ###
