"""empty message

Revision ID: 399e730a73b7
Revises: 2d1f650dc096
Create Date: 2014-04-24 19:53:17.519830

"""

# revision identifiers, used by Alembic.
revision = '399e730a73b7'
down_revision = '2d1f650dc096'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'music', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.drop_column(u'music', 'artist')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'music', sa.Column('artist', sa.VARCHAR(length=128), nullable=True))
    op.drop_column(u'music', 'artist_id')
    op.drop_table('artists')
    ### end Alembic commands ###
