"""empty message

Revision ID: 50f1247803a9
Revises: None
Create Date: 2014-02-01 21:46:22.786212

"""

# revision identifiers, used by Alembic.
revision = '50f1247803a9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
