"""empty message

Revision ID: d5180bb34
Revises: 12a6601db941
Create Date: 2014-09-14 19:22:25.447940

"""

# revision identifiers, used by Alembic.
revision = 'd5180bb34'
down_revision = '12a6601db941'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('created_on', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'created_on')
    ### end Alembic commands ###
